### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by lorcap** [ARMmbed/mbed-flasher#196]
Hi there,

I'm packaging ARM mbed for [Arch Linux](https://www.archlinux.org/). I don't understand the versioning schema for this project. Which is the latest released version? [v0.10.1](https://github.com/ARMmbed/mbed-flasher/releases/tag/v0.10.1) or [pyocd_mbedls_v1710_5](https://github.com/ARMmbed/mbed-flasher/releases/tag/pyocd_mbedls_v1710_5)?

Thanks.

**Comment by juhhov** [comment]
Hi,

[v0.10.1](https://github.com/ARMmbed/mbed-flasher/releases/tag/v0.10.1). If another release is made it will have release page similar to [v0.10.1](https://github.com/ARMmbed/mbed-flasher/releases/tag/v0.10.1) instead of plain tag.
