### ISSUE TITLE
Flash without resetting the board

### ISSUE THREAD

**Issue by RomanSaveljev** [ARMmbed/mbed-flasher#36]
Add special `--no-reset` parameter for `mbedflash flash` sub-command, which will skip touching the serial port. This is preferred by the client, because then it can keep serial port open and skip some error handling.

I do not think it is really necessary to [reset](https://github.com/ARMmbed/mbed-flasher/blob/master/mbed_flasher/flashers/FlasherMbed.py#L192) the board before flashing... DAPlink should do what is necessary. Or is it not so?

Client will reset the board after flasher is done. When a power switch is linked to the board, it will use it. It might be an important feature to support e.g. power consumption profiling in early boot. We flash first and leave the target halted, then client launches power meter recording and unlocks the board's MCU.

**Comment by VeliMattiLahtela** [comment]
enhancement on #40
