### ISSUE TITLE
Force failure of flashing if given binary does not disappear from mount point

### ISSUE THREAD

**Issue by VeliMattiLahtela** [ARMmbed/mbed-flasher#42]
When flashing works correctly flashed binary is flushed from mount point.
Change the flashing validation to fail if binary does not disappear from mount point within 120 seconds.

**Comment by YifeiZuo01** [comment]
There is implementation about this enhancement suggestion.
https://github.com/ARMmbed/mbed-flasher/blob/master/mbed_flasher/mbed_common.py#L74
