### ISSUE TITLE
Re-try on "out-of-order" MSD writing error

### ISSUE THREAD

**Issue by RomanSaveljev** [ARMmbed/mbed-flasher#56]
Daplink emulates MSD. When OS copies a firmware file, it may decide to write blocks in a random order. Daplink can not handle it as it is supposed to write flash contents linearly (there is very little memory for buffering and reordering).

To me it looks like a wrong choice of the feature (MSD), in the first place. Unless we can start using pyOCD for flashing reliably (or try to generate HID packets without it), we need a workaround. Guys in Austin have been working on it.

There is apparently a fork https://github.com/kegilbert/mbed-flasher/commit/2c2731759a7d848109655dee92ce68a06a07021b that covers the implementation. It can be more intelligent and actually look into `FAIL.TXT`. Here is some more info from @c1728p9:

> There are a couple of errors that can occur in that situation, but they all use the same FAIL.TXT mechanism:
"An error occurred during the transfer"
"The transfer timed out."
"Possible mismatch between file size and size programmed"
"File sent out of order by PC. Target might not be programmed correctly."
> Really, as long as the drive don’t contain ASSERT.TXT, it’s probably worth retrying the transfer. If ASSERT.TXT shows up then there is definitely a bug with DAPLink (or USB or computer) that needs to be fixed. If you get an error message that is not one of the above four then it’s likely a DAPLink bug, but does not guarantee that it is a DAPLink bug like ASSERT.TXT does.

**Comment by RomanSaveljev** [comment]
CC: @kegilbert @studavekar @VeliMattiLahtela 

Please correct me, if I compiled the description wrongly

**Comment by studavekar** [comment]
@RomanSaveljev 

Currently what we have seen is when a failure occurs and fail.txt or assert.txt is present, In both cases retrying to flash the device manually passes.

However raas daemon will mark the device in maintenance mode, It is a good feature. However when we have 2 of devices of each kind connected in CI setting one device in maintenance mode causes the test time to almost double.

IMO in either case we should retry at-least in CI environment and it fails after retry count mark the device failure, Intention here is not to mask the any flash related bug but to avoid false failure. We can always report the number of retries.

We have seen most of the times after 2nd retry devices flashes well, If it has to fail even a large count of re-try device will not recover.

Have made few changes for locally testing , which enables usb logging and stores the bin file which failed so we can debug further failure  https://github.com/studavekar/mbed-flasher/commits/remove_failure_file

**Comment by jupe** [comment]
This is covered already in v0.8.0 which do retry when needed..
