### ISSUE TITLE
Not compatible with mbed-ls >=1.3.0?  (use of manufacture_ids)

### ISSUE THREAD

**Issue by maclobdell** [ARMmbed/mbed-flasher#79]
I'm on Windows 10 with mbed-ls version 1.3.4 installed.

looks like mbed-flasher is relying on a method in mbed_lstools (mbed-ls) that went away in mbded-ls v1.3.0.

the manufacture_ids array went away.  After 1.3, now to get the ids, use list_manufacture_ids().  I'm not savvy enough in python to make the needed change.  

Using a test script that relies on update_supported_targets, results in this. 
 
```
   File "C:\Users\maclob01\Documents\mbed-os-5\nanostack-rf-driver-tester.git\test\GenericTestcase.py", line 33, in <module>
    flasher = Flash()
  File "C:\Users\maclob01\Documents\mbed-os-5\nanostack-rf-driver-tester.git\mbed-flasher\mbed_flasher\flash.py", line 42, in __init__
    self.supported_targets = self.__update_supported_targets()
  File "C:\Users\maclob01\Documents\mbed-os-5\nanostack-rf-driver-tester.git\mbed-flasher\mbed_flasher\flash.py", line 65, in __update_supported_targets
    supported_targets = flasher.get_supported_targets()
  File "C:\Users\maclob01\Documents\mbed-os-5\nanostack-rf-driver-tester.git\mbed-flasher\mbed_flasher\flashers\FlasherMbed.py", line 60, in get_supported_targets
    return sorted(set(mbeds.manufacture_ids.values()))
AttributeError: 'MbedLsToolsWin7' object has no attribute 'manufacture_ids'

```

Downgrading mbed-ls to 1.2.16 works, but this looses the new targets that were added after that.  

Please update!

**Comment by adbridge** [comment]
@jonikula Please can you take a look at this as a priority - if you are not the owner of this repo, please advise who is ? Thanks.

**Comment by jupe** [comment]
@adbridge IOTMORF-1657 need to be done first before we can create proper integration with new mbed-ls. #80 is almost ready which brings workaround solution meanwhile.

**Comment by jupe** [comment]
current workaround is not enough, see: https://github.com/ARMmbed/mbed-ls/issues/277. We need to tackle that as well way or another

**Comment by adbridge** [comment]
@jupe I'm assuming the required changes will not be in place in time for the next round of OOB to start - scheduled for tomorrow ?

**Comment by jupe** [comment]
We doesn’t have mbed-ls fixes/API’s yet so no, won’t be ready for tomorrow. @bridadan could you give any estimate when we could have mbed-ls ready for this?

**Comment by bridadan** [comment]
I don't have an estimate at the moment, but I'll try to prioritize this. I'll update here

**Comment by MarceloSalazar** [comment]
@bridadan what's the status of this?
Do we need anything else to get https://github.com/ARMmbed/nanostack-rf-driver-tester/issues/12 resolved?

**Comment by bridadan** [comment]
@jupe will a new version of mbed-flasher be released with the patch you already proposed? Or are you waiting on https://github.com/ARMmbed/mbed-ls/pull/280 to go in?

**Comment by MarceloSalazar** [comment]
@jupe can you please comment on this?

**Comment by jupe** [comment]
yep this: https://github.com/ARMmbed/mbed-ls/pull/280
and IOTMORF-1657 need to be in release.
